# Курс "Линейная алгебра"

## Урок 2. Матрицы и матричные операции

### Домашняя работа к уроку 2

In [1]:
import numpy as np
import math

#### Задание 1

Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

Исходя из определения __матрицей__ размера $m\times n$ называется прямоугольная таблица, состоящая из $m$ строк и $n$ столбцов, можем заключить 

а)

In [2]:
A = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

In [3]:
B = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

In [4]:
# np.dot(A, B)

In [5]:
# np.dot(B, A)

б)

In [6]:
A = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [7]:
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])

In [8]:
np.dot(A, B)

array([[135, 150, 165],
       [310, 350, 390]])

In [9]:
# np.dot(B, A)

в)

In [10]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]])

In [11]:
B = np.array([[1, 2, 3, 4, 5, 6, 7, 8], [9, 10, 11, 12, 13, 14, 15, 16], [17, 18, 19, 20, 21, 22, 23, 24]])

In [12]:
np.dot(A, B)

array([[  70,   76,   82,   88,   94,  100,  106,  112],
       [ 151,  166,  181,  196,  211,  226,  241,  256],
       [ 232,  256,  280,  304,  328,  352,  376,  400],
       [ 313,  346,  379,  412,  445,  478,  511,  544],
       [ 394,  436,  478,  520,  562,  604,  646,  688],
       [ 475,  526,  577,  628,  679,  730,  781,  832],
       [ 556,  616,  676,  736,  796,  856,  916,  976],
       [ 637,  706,  775,  844,  913,  982, 1051, 1120]])

In [13]:
np.dot(B, A)

array([[ 540,  576,  612],
       [1276, 1376, 1476],
       [2012, 2176, 2340]])

г)

In [14]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

In [15]:
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

In [16]:
np.dot(A, B)

array([[ 90, 100, 110, 120],
       [202, 228, 254, 280],
       [314, 356, 398, 440],
       [426, 484, 542, 600]])

In [17]:
np.dot(B, A)

array([[ 90, 100, 110, 120],
       [202, 228, 254, 280],
       [314, 356, 398, 440],
       [426, 484, 542, 600]])

#### Задание 2

Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [18]:
A = np.array([[1, -2], [3, 0]])

In [19]:
B = np.array([[4, -1], [0, 5]])

In [20]:
A + B

array([[ 5, -3],
       [ 3,  5]])

In [21]:
np.dot(A, B)

array([[  4, -11],
       [ 12,  -3]])

#### Задание 3

Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [22]:
A = np.array([[1, 7], [3, -6]])

In [23]:
B = np.array([[0, 5], [2, -1]])

In [24]:
C = np.array([[2, -4], [1, 1]])

In [25]:
3 * 𝐴 - 2 * 𝐵 + 4 * 𝐶

array([[ 11,  -5],
       [  9, -12]])

#### Задание 4

Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [26]:
A = np.array([[4, 1], [5, -2], [2, 3]])

In [27]:
np.dot(A, A.T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [28]:
np.dot(A.T, A)

array([[45,  0],
       [ 0, 14]])

#### Задание 5*

Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [29]:
def dot(A, B):
    if (len(A[0]) != len(B)):
        raise ValueError('Порядки перемножаемых матриц не соответствуют правилу умножения матриц.')
    count_i = len(A)
    count_j = len(A[0])
    count_k = len(B[0])
    result = [[0 for k in range(count_k)] for l in range(count_i)]
    for i in range(count_i):
        for k in range(count_k):
            for j in range(count_j):
                result[i][k] += A[i][j] * B[j][k]
    return result

In [30]:
A = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [31]:
B = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]]

In [32]:
dot(A, B)

[[135, 150, 165], [310, 350, 390]]

In [33]:
# dot(B, A)

In [34]:
print(np.dot(np.array(A), np.array(B)))

[[135 150 165]
 [310 350 390]]


#### Задание 1

Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

In [35]:
x = math.pi / 2
A = np.array([[math.sin(x), -math.cos(x)], [math.cos(x), math.sin(x)]])

In [36]:
np.linalg.det(A)

1.0

In [37]:
A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])

In [38]:
np.linalg.det(A)

180.0

In [39]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [40]:
np.linalg.det(A)

6.66133814775094e-16

#### Задание 2

Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

In [41]:
A = np.array([[2, 1], [2, 3]])

In [42]:
np.linalg.det(A)

4.0

In [43]:
np.linalg.det(np.dot(A, A))

15.999999999999998

In [44]:
np.linalg.det(A.T)

4.0

In [45]:
2 * A

array([[4, 2],
       [4, 6]])

In [46]:
np.linalg.det(2 * A)

15.999999999999998

In [47]:
4 * 6 - 4 * 2

16

Согласно пункту 2:

__2.__ Умножение строки или столбца матрицы на число $\lambda$ приведет к умножению определителя матрицы на то же число. 

- Доказательство этого свойства элементарно, так как, исходя из формулы определителя, множитель из этой строки будет в каждом из слагаемых при нахождении определителя разложением по этой строке/столбцу, что равнозначно его умножению на это число.

должно было получиться $8$.

Но это неправильно, так как при умножении всех элементов матрицы, мы выносим за скобки не просто число $\lambda$, а $\lambda^n$, где $n$ ранг матрицы.

Правильный ответ: $(2 \cdot 2)\cdot(2 \cdot 3) - (2 \cdot 1)\cdot(2 \cdot 2) = 2^2\cdot(2\cdot3-1\cdot2) = 4\cdot(6 - 2) = 4\cdot4 = 16$

#### Задание 3

Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

In [48]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])

In [49]:
np.linalg.det(A)

0.0

#### Задание 4

Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [50]:
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])

In [51]:
np.linalg.matrix_rank(A)

2

In [52]:
A = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])

In [53]:
np.linalg.matrix_rank(A)

3