In [1]:
import numpy as np
import scipy.linalg

In [23]:
a = np.array([[2, 1, 1], [4, -6, 0], [-2, 7, 2]])
b = np.array([5, -2, 9])
detA = np.linalg.det(a)

In [24]:
print (f'det A:\n {detA}\n')

det A:
 -15.999999999999998



In [25]:
a1=np.column_stack([b,a[:,1:]])
detA1=np.linalg.det(a1)
print (f'a1:\n {a1}\n')

a1:
 [[ 5  1  1]
 [-2 -6  0]
 [ 9  7  2]]



In [26]:
a2=np.column_stack([a[:,0], b, a[:,2]])
detA2=np.linalg.det(a2)
print (f'a2:\n {a2}\n')

a2:
 [[ 2  5  1]
 [ 4 -2  0]
 [-2  9  2]]



In [27]:
a3=np.column_stack([a[:,0:2], b])
detA3=np.linalg.det(a3)
print (f'a3:\n {a3}\n')

a3:
 [[ 2  1  5]
 [ 4 -6 -2]
 [-2  7  9]]



In [28]:
print (f'x1= {detA1 /detA}\n')
print (f'x2= {detA2 /detA}\n')
print (f'x3= {detA3 /detA}\n')

x1= 1.0000000000000007

x2= 0.9999999999999996

x3= 2.0000000000000004



In [30]:
a = np.array([[2, 1, -1], [4, -6, -2], [-2, 7, -3]])
b = np.array([5, -2, 7])
lu, piv = scipy.linalg.lu_factor(a)
x= scipy.linalg.lu_solve((lu,piv), b)

In [46]:
print (f'a:\n {a}\n')
print (f'b:\n {b}\n')
print (f'x:\n {x}\n')
print (f'Ax:\n {a @ x}\n')

a:
 [[ 2  1 -1]
 [ 4 -6 -2]
 [-2  7 -3]]

b:
 [ 5 -2  7]

x:
 [ 1.75  1.5  -0.  ]

Ax:
 [ 5. -2.  7.]



In [48]:
a = np.array([[2, 1, 1], [4, -6, 0], [-2, 7, 2]])
b = np.array([5, -2, 9])
x = scipy.linalg.solve(a,b)
print (f'x:\n {x}\n')

x:
 [1. 1. 2.]

